name: Test

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Run Tests
        run: dotnet test
        shell: pwsh